services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT:-8080}:8080"
    restart: unless-stopped
    volumes:
      - ./apps/api/src:/app/src
      - ./apps/api/prisma:/app/prisma

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:80"
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
      - ./apps/web/vite.config.ts:/app/vite.config.ts
